Repository Alwatr/nitrobase, pull requests merged in 2023-12, with the labels that each got.

#163 chore:(ci/dependabot): schedule
  .github/dependabot.yml
  .vscode/settings.json
Labels: ci

#166 feat: new AlwatrStore engine v5
  demo/engine/collection.ts
  demo/engine/doc.ts
  demo/node-fs/multi-write.ts
  demo/package.json
  demo/tsconfig.json
  packages/engine5/README.md
  packages/engine5/package.json
  packages/engine5/src/alwatr-store.ts
  packages/engine5/src/demo-col.ts
  packages/engine5/src/demo-doc.ts
  packages/engine5/src/lib/collection-reference.ts
  packages/engine5/src/lib/document-reference.ts
  packages/engine5/src/lib/logger.ts
  packages/engine5/src/lib/util.ts
  packages/engine5/src/main.ts
  packages/engine5/src/type.ts
  packages/engine5/tsconfig.json
  packages/nginx/.dockerignore
  packages/nginx/Dockerfile
  packages/nginx/default-data/_error.json
  packages/nginx/etc/nginx/templates/http.d/31-store-mime-types.conf.template
  packages/nginx/etc/nginx/templates/http.d/49-map-bearer-token.conf.template
  packages/nginx/etc/nginx/templates/http.d/49-map-headers.conf.template
  packages/nginx/etc/nginx/templates/location.d/90-home-json.conf.template
  packages/nginx/etc/nginx/templates/location.d/91-json.conf.template
  yarn.lock
Labels: breaking-change

#181 feat: Refactor DocumentReference logger
  packages/store-reference/src/collection-reference.ts
  packages/store-reference/src/document-reference.ts
Labels: new-feature

#183 feat: Refactor code and fix import statements
  .vscode/settings.json
  packages/engine/.gitignore
  packages/engine/demo/benchmark.mjs
  packages/engine/demo/collection.mjs
  packages/engine/demo/data-lost-test.js
  packages/engine/demo/doc.mjs
  packages/engine/package.json
  packages/engine/src/alwatr-store.ts
  packages/engine/src/lib/node-fs.ts
  packages/engine/src/lib/store-file-stat.ts
  packages/engine/src/main.ts
  packages/engine/tsconfig.json
  packages/reference/README.md
  packages/reference/demo/collection.mjs
  packages/reference/package.json
  packages/reference/src/collection-reference.ts
  packages/reference/src/document-reference.ts
  packages/reference/src/logger.ts
  packages/reference/src/main.ts
  packages/reference/src/util.ts
  packages/reference/tsconfig.json
  packages/store-reference/src/main.ts
  packages/types/src/main.ts
  yarn.lock
Labels: new-feature

#184 feat: Enhance saving data and prevent data list strategy
  package.json
  packages/engine/demo/benchmark.mjs
  packages/engine/demo/data-lost-test.js
  packages/engine/package.json
  packages/engine/src/alwatr-store.ts
  packages/engine/src/logger.ts
  packages/reference/src/collection-reference.ts
  packages/reference/src/document-reference.ts
Labels: new-feature
